version: "3.7"

services:
  front:
    container_name: front
    working_dir: /srv/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/srv/app
